blank_issues_enabled: true
contact_links:
  - name: Chat de Discord
    url: https://discord.gg/5qBzk2fv
    about: Realiza preguntas y debates en el canal de Discord de Svelte en español.
  - name: Chat de Telegram
    url: https://t.me/sveltekit_dev
    about: Realiza preguntas y debates en el canal de Telegram de Svelte en español

