name: 'Importante'
description: 'Nota importante'
body:
  - type: markdown
    attributes: 
      value: # Atención

  - type: markdown
    attributes:
      value: | 
        Está a punto de abrir una issue sobre el proyecto de traducción de la documentación de Svelte al español.
        Este proyecto está dedicado únicamente a la traducción, por lo que solo se aceptarán issues cuya finalidad sea añadir o modificar traducciones, o cualquier herramienta asociada.
        Para cualquier problema relacionado con el proyecto Svelte en sí, ábrelo en el [repositorio oficial](https://github.com/sveltejs/svelte/issues).
